.TH DOCCENTRAL 1 "Debian tools" "DEBIAN"
.SH NAME
doccentral \- web\-based documentation browser
.SH SYNOPSIS
.B doccentral
[\fIdocument-name\fR]
.SH OPTIONS
.PP
The only option that can be passed to the doccentral wrapper is a document
name (often the same as the name of the package which provides it) for
direct access (automatic search for the given parameter).
.SH DESCRIPTION
.B Doc-Central
is a simple tool to help you browse the documentation installed on your
.B Debian
system. It uses the
.I doc-base
registration entries for documentation to build a list of available documentation.
You can view this list via any web browser.
.PP
The easiest way to view the
.B doc-central
index is to use the
.B doccentral
tool, which will look for a webbrowser on your system and start that
with the correct page. If for any reason
.B doccentral
cannot find a suitable browser or you want to use another one, you can also
use the following URL:
.PP
.RS
.UR http://localhost/dc/
http://localhost/dc/
.UE
.RE
.SH ENVIRONMENT
.TP
BROWSER
Override the normal browser selection from
.B doccentral
by specifying a specific browser.
.TP
DC_HOST
Override the location of
.B Doc-Central
(usually localhost)
.SH AUTHOR
Guilherme de S. Pastore
.UR mailto:guilherme.pastore@terra.com.br
<guilherme.pastore@terra.com.br>
.UE
.br
Wichert Akkerman
.UR mailto:wakkerma@debian.org
<wakkerma@debian.org>
.UE
