#!/bin/sh

set -e

if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
    . /usr/share/apache2/apache2-maintscript-helper
    apache2_invoke enconf doc-central.conf || exit $?
fi

#DEBHELPER#